<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RecipeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('recipes')->insert([
            [
                'name' => 'Greek Salad',
                'ingredients' => '2 cucumbers, 3 large tomatoes, 200g feta cheese, 100g olives, 1 red onion, 3 tbsp olive oil',
                'instructions' => "1. Wash and chop cucumbers and tomatoes.\n2. Slice the red onion.\n3. Combine cucumbers, tomatoes, red onion, and olives in a bowl.\n4. Crumble feta cheese over the mixture.\n5. Drizzle with olive oil and toss gently to combine.",
                'preparation_time' => 10,
                'image' => asset('images/recipe-images/GS.png'),
                'cuisine_id' => 1,
                'category_id' => 3, 
                'macro_id' => 1,
            ],
            [
                'name' => 'Apple Pie',
                'ingredients' => '6 apples (peeled and sliced), 100g sugar, 2 tbsp flour, 50g butter, 1 tsp cinnamon, 1 pie crust',
                'instructions' => "1. Preheat the oven to 180°C (350°F).\n2. Combine apples, sugar, flour, and cinnamon.\n3. Roll out the pie crust and add filling.\n4. Top with butter.\n5. Cover with another crust and make slits.\n6. Bake for 45 minutes or until golden brown.",
                'preparation_time' => 45,
                'image' => asset('images/recipe-images/AP.png'),
                'cuisine_id' => 2,
                'category_id' => 4, 
                'macro_id' => 2,
            ],
            [
                'name' => 'Chicken Tacos',
                'ingredients' => '300g chicken breast, 6 tortillas, 100g salsa, 1 avocado (sliced), 1 lime, 50g grated cheese',
                'instructions' => "1. Season and cook the chicken.\n2. Warm tortillas.\n3. Fill with chicken, salsa, avocado, and cheese.\n4. Squeeze lime on top before serving.",
                'preparation_time' => 20,
                'image' => asset('images/recipe-images/CT.png'),
                'cuisine_id' => 3,
                'category_id' => 1, 
                'macro_id' => 3,
            ],
            [
                'name' => 'French Fries',
                'ingredients' => '4 large potatoes, 1 liter oil for frying, 1 tsp salt',
                'instructions' => "1. Peel and cut potatoes into strips.\n2. Soak in water to remove starch.\n3. Heat oil to 180°C.\n4. Dry and fry until golden.\n5. Season with salt.",
                'preparation_time' => 25,
                'image' => asset('images/recipe-images/FF.png'),
                'cuisine_id' => 4,
                'category_id' => 2, 
                'macro_id' => 4,
            ],
            [
                'name' => 'Garlic Bread',
                'ingredients' => '1 baguette, 50g butter, 3 cloves garlic (minced), 2 tbsp parsley (chopped)',
                'instructions' => "1. Preheat oven to 200°C (400°F).\n2. Mix butter, garlic, and parsley.\n3. Slice baguette diagonally.\n4. Spread garlic butter.\n5. Wrap in foil and bake for 10 minutes.\n6. Unwrap and bake 5 more minutes.",
                'preparation_time' => 10,
                'image' => asset('images/recipe-images/GB.png'),
                'cuisine_id' => 1,
                'category_id' => 5, 
                'macro_id' => 5,
            ],
            [
                'name' => 'Vegetable Stir-fry',
                'ingredients' => '2 carrots (sliced), 1 broccoli head (florets), 1 bell pepper (sliced), 2 tbsp soy sauce, 1 tbsp sesame oil',
                'instructions' => "1. Heat sesame oil in a wok.\n2. Stir-fry carrots for 3 minutes.\n3. Add broccoli and peppers.\n4. Drizzle soy sauce and stir.\n5. Serve over rice or noodles.",
                'preparation_time' => 15,
                'image' => asset('images/recipe-images/VS.png'),
                'cuisine_id' => 5,
                'category_id' => 2, 
                'macro_id' => 6,
            ],
            [
                'name' => 'Beef Stroganoff',
                'ingredients' => '500g beef strips, 200g mushrooms, 1 onion, 200ml sour cream, 1 tbsp paprika',
                'instructions' => "1. Brown beef strips.\n2. Sauté onions and mushrooms.\n3. Add paprika and beef.\n4. Stir in sour cream.\n5. Serve over noodles or potatoes.",
                'preparation_time' => 30,
                'image' => asset('images/recipe-images/BS.png'),
                'cuisine_id' => 4,
                'category_id' => 1,
                'macro_id' => 7,
            ],
            [
                'name' => 'Vegetarian Pizza',
                'ingredients' => '1 pizza base, 100g tomato sauce, 100g mozzarella, 50g mushrooms, 50g bell peppers, 50g olives',
                'instructions' => "1. Preheat oven to 220°C.\n2. Spread sauce.\n3. Add cheese and toppings.\n4. Bake 12-15 minutes.",
                'preparation_time' => 20,
                'image' => asset('images/recipe-images/VP.png'),
                'cuisine_id' => 5,
                'category_id' => 1, 
                'macro_id' => 8,
            ],
            [
                'name' => 'Shrimp Scampi',
                'ingredients' => '300g shrimp, 3 garlic cloves (minced), 50g butter, 2 tbsp lemon juice, 200g spaghetti',
                'instructions' => "1. Cook spaghetti.\n2. Sauté garlic in butter.\n3. Add shrimp.\n4. Toss with lemon juice and spaghetti.",
                'preparation_time' => 20,
                'image' => asset('images/recipe-images/SS.png'),
                'cuisine_id' => 3,
                'category_id' => 1, 
                'macro_id' => 9,
            ],
            [
                'name' => 'Pancakes',
                'ingredients' => '200g flour, 2 tbsp sugar, 1 tsp baking powder, 2 eggs, 300ml milk, 50g butter',
                'instructions' => "1. Mix dry ingredients.\n2. Whisk in eggs and milk.\n3. Heat butter in a skillet.\n4. Pour batter, flip when bubbly.\n5. Serve with syrup.",
                'preparation_time' => 15,
                'image' => asset('images/recipe-images/PC.png'),
                'cuisine_id' => 2,
                'category_id' => 4, 
                'macro_id' => 10,
            ],
            [
                'name' => 'Chicken Alfredo',
                'ingredients' => '300g chicken breast, 200g fettuccine, 100ml cream, 50g Parmesan cheese, 2 garlic cloves',
                'instructions' => "1. Cook fettuccine.\n2. Cook chicken, slice.\n3. Sauté garlic, add cream & cheese.\n4. Toss with pasta.\n5. Top with chicken.",
                'preparation_time' => 30,
                'image' => asset('images/recipe-images/CA.png'),
                'cuisine_id' => 5,
                'category_id' => 1, 
                'macro_id' => 11,
            ],
            [
                'name' => 'Caesar Salad',
                'ingredients' => '1 romaine lettuce, 50g croutons, 30g Parmesan, 3 tbsp Caesar dressing',
                'instructions' => "1. Chop romaine.\n2. Toss with dressing and croutons.\n3. Top with Parmesan.\n4. Serve immediately.",
                'preparation_time' => 10,
                'image' => asset('images/recipe-images/CS.png'),
                'cuisine_id' => 4,
                'category_id' => 3, 
                'macro_id' => 12,
            ],
            [
                'name' => 'Tom Yum Soup',
                'ingredients' => '500ml chicken broth, 200g shrimp, 1 lemongrass stalk, 2 lime leaves, 2 tbsp fish sauce, 2 chili peppers',
                'instructions' => "1. Heat broth.\n2. Add lemongrass, lime leaves, fish sauce, chili.\n3. Simmer 10 minutes.\n4. Add shrimp.\n5. Cook until pink.",
                'preparation_time' => 20,
                'image' => asset('images/recipe-images/TS.png'),
                'cuisine_id' => 6,
                'category_id' => 2, 
                'macro_id' => 13,
            ],
            [
                'name' => 'Butter Chicken',
                'ingredients' => '300g chicken, 200ml tomato puree, 100ml cream, 50g butter, 2 tsp garam masala',
                'instructions' => "1. Cook chicken in butter.\n2. Add tomato puree & garam masala.\n3. Simmer 15 minutes.\n4. Stir in cream.\n5. Serve with naan or rice.",
                'preparation_time' => 30,
                'image' => asset('images/recipe-images/BC.png'),
                'cuisine_id' => 7,
                'category_id' => 1, 
                'macro_id' => 14,
            ],
            [
                'name' => 'Pad Thai',
                'ingredients' => '200g rice noodles, 100g shrimp, 1 egg, 2 tbsp tamarind paste, 1 tbsp fish sauce, 50g peanuts',
                'instructions' => "1. Cook noodles.\n2. Sauté shrimp.\n3. Scramble egg.\n4. Add tamarind paste, fish sauce, noodles.\n5. Top with crushed peanuts.",
                'preparation_time' => 25,
                'image' => asset('images/recipe-images/PT.png'),
                'cuisine_id' => 6,
                'category_id' => 1, 
                'macro_id' => 15,
            ],
            [
                'name' => 'Ratatouille',
                'ingredients' => '1 eggplant, 1 zucchini, 1 bell pepper, 1 onion, 2 tomatoes, 2 tbsp olive oil',
                'instructions' => "1. Slice vegetables.\n2. Layer in a skillet with olive oil.\n3. Cover and cook 30 minutes.\n4. Serve warm.",
                'preparation_time' => 40,
                'image' => asset('images/recipe-images/RT.png'),
                'cuisine_id' => 4,
                'category_id' => 2, 
                'macro_id' => 16,
            ],
            [
                'name' => 'Tiramisu',
                'ingredients' => '200g ladyfingers, 250g mascarpone, 2 eggs, 100g sugar, 300ml coffee, cocoa powder',
                'instructions' => "1. Beat egg yolks with sugar.\n2. Fold in mascarpone.\n3. Dip ladyfingers in coffee.\n4. Layer with mascarpone.\n5. Dust with cocoa.\n6. Chill 4 hours.",
                'preparation_time' => 20,
                'image' => asset('images/recipe-images/TR.png'),
                'cuisine_id' => 5,
                'category_id' => 4, 
                'macro_id' => 17,
            ],
            [
                'name' => 'Gulab Jamun',
                'ingredients' => '200g khoya, 50g flour, 1 tsp baking soda, 200ml sugar syrup, oil for frying',
                'instructions' => "1. Mix khoya, flour, baking soda.\n2. Shape into balls.\n3. Fry until golden.\n4. Soak in sugar syrup 30 minutes.\n5. Serve warm or chilled.",
                'preparation_time' => 30,
                'image' => asset('images/recipe-images/GJ.png'),
                'cuisine_id' => 7,
                'category_id' => 4, 
                'macro_id' => 18,
            ],
            [
                'name' => 'Shepherd’s Pie',
                'ingredients' => '500g ground beef, 1 onion (diced), 2 carrots (diced), 200ml beef broth, 500g mashed potatoes',
                'instructions' => "1. Brown beef with onions and carrots.\n2. Add broth, simmer 10 minutes.\n3. Transfer to a dish, top with mashed potatoes.\n4. Bake 25 minutes at 200°C.",
                'preparation_time' => 40,
                'image' => asset('images/recipe-images/SP.jpg'),
                'cuisine_id' => 2,
                'category_id' => 1,
                'macro_id' => 19,
            ],
            [
                'name' => 'Falafel',
                'ingredients' => '400g chickpeas, 2 garlic cloves, 1 onion, 2 tbsp parsley, 1 tsp cumin, oil for frying',
                'instructions' => "1. Blend chickpeas, garlic, onion, parsley, cumin.\n2. Shape into balls.\n3. Fry until golden.\n4. Serve in pita with tahini.",
                'preparation_time' => 30,
                'image' => asset('images/recipe-images/FL.png'),
                'cuisine_id' => 1,
                'category_id' => 5, 
                'macro_id' => 20,
            ],
            [
                'name' => 'Shakshuka',
                'ingredients' => '4 eggs, 1 onion (diced), 2 bell peppers (diced), 400g canned tomatoes, 2 garlic cloves, 2 tbsp olive oil, 1 tsp cumin, 1 tsp paprika',
                'instructions' => "1. Heat olive oil in a skillet.\n2. Sauté onions, peppers, and garlic until soft.\n3. Add tomatoes, cumin, and paprika. Simmer for 10 minutes.\n4. Make small wells and crack eggs into them.\n5. Cover and cook until eggs are set.\n6. Serve with crusty bread.",
                'preparation_time' => 20,
                'image' => asset('images/recipe-images/SH.png'),
                'cuisine_id' => 10, 
                'category_id' => 2, 
                'macro_id' => 21,
            ],
            [
                'name' => 'Rogan Josh',
                'ingredients' => '500g lamb, 2 onions, 3 garlic cloves, 200g yogurt, 2 tsp garam masala, 1 tsp turmeric, 1 tsp paprika, 2 tbsp ghee',
                'instructions' => "1. Heat ghee in a pot.\n2. Sauté onions and garlic until golden.\n3. Add lamb and spices. Cook until browned.\n4. Stir in yogurt and simmer for 40 minutes.\n5. Serve with naan or basmati rice.",
                'preparation_time' => 50,
                'image' => asset('images/recipe-images/RJ.png'),
                'cuisine_id' => 8, 
                'category_id' => 1, 
                'macro_id' => 22,
            ],
            [
                'name' => 'Paella Valenciana',
                'ingredients' => '300g chicken thighs, 200g shrimp, 1 onion, 2 tomatoes, 200g rice, 500ml chicken broth, 1 tsp saffron, 2 tbsp olive oil',
                'instructions' => "1. Heat olive oil in a large skillet.\n2. Sauté chicken until browned. Remove and set aside.\n3. Cook onions and tomatoes until soft.\n4. Add rice, saffron, and broth.\n5. Return chicken and add shrimp.\n6. Cover and cook until rice is done.",
                'preparation_time' => 45,
                'image' => asset('images/recipe-images/PV.png'),
                'cuisine_id' => 11, 
                'category_id' => 1, 
                'macro_id' => 23,
            ],
            [
                'name' => 'Okonomiyaki',
                'ingredients' => '200g cabbage (shredded), 2 eggs, 100g flour, 50ml dashi stock, 50g bacon, okonomiyaki sauce, mayonnaise, seaweed flakes',
                'instructions' => "1. Mix cabbage, eggs, flour, and dashi stock in a bowl.\n2. Heat oil in a skillet. Pour in batter to form a pancake.\n3. Place bacon on top and cook until golden.\n4. Flip and cook the other side.\n5. Drizzle with okonomiyaki sauce and mayonnaise. Garnish with seaweed flakes.",
                'preparation_time' => 25,
                'image' => asset('images/recipe-images/OK.png'),
                'cuisine_id' => 7, 
                'category_id' => 5, 
                'macro_id' => 24,
            ],
            [
                'name' => 'Moussaka',
                'ingredients' => '2 eggplants, 500g ground beef, 2 tomatoes, 1 onion, 2 potatoes, 200ml béchamel sauce, 2 tbsp olive oil',
                'instructions' => "1. Slice and grill eggplants and potatoes.\n2. Sauté onions, ground beef, and tomatoes.\n3. Layer eggplants, potatoes, and beef in a baking dish.\n4. Pour béchamel sauce on top.\n5. Bake at 180°C for 30 minutes.",
                'preparation_time' => 45,
                'image' => asset('images/recipe-images/MS.png'),
                'cuisine_id' => 1, 
                'category_id' => 1, 
                'macro_id' => 25,
            ],
            [
                'name' => 'Empanadas',
                'ingredients' => '300g ground beef, 1 onion, 2 garlic cloves, 1 tsp paprika, 1 tsp cumin, 200g empanada dough, oil for frying',
                'instructions' => "1. Sauté onion and garlic until soft.\n2. Add ground beef and spices. Cook until browned.\n3. Roll out dough and cut into circles.\n4. Place filling in the center and fold over to seal.\n5. Fry until golden brown.",
                'preparation_time' => 35,
                'image' => asset('images/recipe-images/EP.png'),
                'cuisine_id' => 11, 
                'category_id' => 5, 
                'macro_id' => 26,
            ],
            [
                'name' => 'Chili Con Carne',
                'ingredients' => '500g ground beef, 1 onion, 2 garlic cloves, 1 bell pepper, 400g canned tomatoes, 200g kidney beans, 1 tsp chili powder, 1 tsp cumin',
                'instructions' => "1. Sauté onions, garlic, and bell peppers.\n2. Add ground beef and cook until browned.\n3. Stir in tomatoes, kidney beans, and spices.\n4. Simmer for 20 minutes.\n5. Serve with rice or tortilla chips.",
                'preparation_time' => 30,
                'image' => asset('images/recipe-images/CCC.png'),
                'cuisine_id' => 2, 
                'category_id' => 1, 
                'macro_id' => 27,
            ],
            [
                'name' => 'Baklava',
                'ingredients' => '200g phyllo dough, 100g walnuts, 100g pistachios, 100g sugar, 100g butter, 100ml honey, 1 tsp cinnamon',
                'instructions' => "1. Chop nuts and mix with sugar and cinnamon.\n2. Layer phyllo sheets with butter and nut mixture in a baking dish.\n3. Bake at 180°C for 25 minutes.\n4. Pour honey over warm baklava and let cool.",
                'preparation_time' => 40,
                'image' => asset('images/recipe-images/BK.png'),
                'cuisine_id' => 10, 
                'category_id' => 4, 
                'macro_id' => 28,
            ],
            [
                'name' => 'Pho',
                'ingredients' => '200g rice noodles, 500ml beef broth, 200g beef slices, 2 star anise, 1 cinnamon stick, 2 green onions, 1 tbsp fish sauce',
                'instructions' => "1. Simmer beef broth with star anise and cinnamon for 20 minutes.\n2. Cook noodles according to package instructions.\n3. Place noodles in a bowl, top with beef slices.\n4. Pour hot broth over and garnish with green onions.",
                'preparation_time' => 30,
                'image' => asset('images/recipe-images/BF.png'),
                'cuisine_id' => 6, 
                'category_id' => 2, 
                'macro_id' => 29,
            ],
            [
                'name' => 'Ceviche',
                'ingredients' => '200g fresh fish (cubed), 2 limes, 1 red onion, 1 chili pepper, 2 tbsp cilantro',
                'instructions' => "1. Dice fish into small cubes.\n2. Mix with lime juice and let sit for 10 minutes.\n3. Add diced onions, chili, and cilantro.\n4. Serve chilled.",
                'preparation_time' => 20,
                'image' => asset('images/recipe-images/CH.png'),
                'cuisine_id' => 10, 
                'category_id' => 3, 
                'macro_id' => 30,
            ],
        ]);
    }
}
